extension = "bf"
command = "brainfuck $FILE"

[tests.helloWorld]
_main = """
-[------->+<]>-.
-[->+++++<]>++.
+++++++.
.
+++.
[--->+<]>-----.
---[->+++<]>.
-[--->+<]>---.
+++.
------.
--------.
>++++++++++.
"""
