extension = "cob"
command = "cobc -xj $FILE"

[tests.helloWorld]
_main = """
       identification division.
       program-id. hello.
       procedure division.
           display 'Hello World'.
"""
